### ISSUE TITLE
Mistakes in determiner_noun_agreement_with_adjective_1

### ISSUE THREAD

**Issue by jumelet** [alexwarstadt/blimp#3]
Hi! First of all thanks a lot for this fantastic resource, it has been really helpful in my research.

I stumbled upon a few mistakes in the `determiner_noun_agreement_with_adjective_1` template, of which I wasn't sure if you were aware of them:

1. The template name does not match with the name in Table 4 (`determiner_noun_agreement_with_adj_1`).
2. The unacceptable example in Table 4 is the same as the acceptable example (_Tracy praises those lucky guys_).
3. There appear a few ungrammatical sentences in the corpus, such as pairID 37: _Tonya helps these out in the open doctors._, and pairID 84: _Wendy did attack that out in the open senator._. It seems that all these incorrect items contain the determiner "the", paired with some incorrect noun phrase that in all case seems to contain the adjective "open".

If I counted it correctly 23 out of the 1000 items seem to contain the mistake of #3, so it wouldn't have that big of an impact on performance.

**Comment by jumelet** [comment]
I'm looking in more detail at the other determiner noun agreement tasks as well, and it seems this mistake is also present in all the other determiner tasks that contain the added adjective.

E.g.: _That committee works with those out in the open women._ in `determiner_noun_agreement_with_adj_irregular_1`

**Comment by alexwarstadt** [comment]
Hi Jaap! Thanks for bringing these to our attention. We will update table 4 on arXiv. 

For these weird examples, fortunately, even if both sentences in the pair have very low probability, we still expect the one with agreement to be higher, so the examples are still usable in theory. For what it's worth, I think these sentences are marginal, and would be slightly better if they had hyphens (Wendy did attack that out-in-the-open senator.).

If you're curious, the problem seems to have been that we classified "out in the open" as an adjective because it can occur predicatively, but it is not very good prenominally.

**Comment by alexwarstadt** [comment]
p.s. I'm very glad that BLiMP has been useful! 

And I saw your recent paper on analyzing subtasks within language modeling. Very excited to read it!

**Comment by jumelet** [comment]
Ahhh now I get those sentences, that makes perfect sense indeed! Thanks a lot for your quick response.
